volumes:
  config:
    driver: local
  data:
    driver: local
  runner:
    driver: local
  logs:  # Ajout du volume manquant pour les logs
    driver: local

services:
  gitlab:
    restart: unless-stopped
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '8085:80'
      - '2222:22'
    volumes:
      - 'data:/var/opt/gitlab'
      - 'config:/etc/gitlab'
      - 'logs:/var/log/gitlab'  # Volume des logs maintenant défini

  gitlab-runner:
    restart: unless-stopped
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'runner:/etc/gitlab-runner'
      - 'config:/etc/gitlab'
