version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest  # Utilisez la dernière version de l'édition communautaire (CE)
    container_name: gitlab
    hostname: 'gitlab.example.com'  # Remplacez par le nom d'hôte que vous voulez utiliser
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'  # Remplacez par l'URL que vous souhaitez utiliser pour accéder à GitLab
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '80:80'     # Pour HTTP
      - '443:443'   # Pour HTTPS
      - '2222:22'   # Pour SSH (facultatif)
    volumes:
      - gitlab-config:/etc/gitlab    # Configuration GitLab persistante
      - gitlab-logs:/var/log/gitlab  # Logs persistants
      - gitlab-data:/var/opt/gitlab  # Données GitLab persistantes
    restart: always

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

