---
- name: Mettre à jour le fichier creationUser.sh sur toutes les VM
  hosts: mes_vms
  vars:
  # Ajout des variables SSH dans le playbook
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Copier le fichier creationUser.sh dans le répertoire /script_perso
      copy:
        # src: /chemin/local/vers/creationUser.sh
        src: C:/AJC_formation/algorithmie/creationUser.ssh
        dest: /script_perso/creationUser.sh
        owner: vboxuser
        mode: '0755'
