apiVersion: apps/v1  # Version de l'API Kubernetes utilisée pour le déploiement
kind: Deployment     # Type de ressource, ici un déploiement
metadata:
  labels:           # Étiquettes pour identifier le déploiement
    app: web       # Nom de l'application
  name: web        # Nom du déploiement
spec:
  replicas: 2      # Nombre de réplicas souhaités pour le déploiement
  selector:        # Sélecteur pour identifier les pods gérés par ce déploiement
    matchLabels:
      app: web    # Étiquette à faire correspondre pour sélectionner les pods
  template:       # Modèle de pod à créer
    metadata:
      labels:     # Étiquettes pour les pods créés par ce déploiement
        app: web  # Nom de l'application pour les pods
    spec:
      containers: # Liste des conteneurs à déployer dans les pods
      - image: zwindler/vhelloworld  # Image du conteneur à utiliser
        name: web  # Nom du conteneur
