apiVersion: v1  # Version de l'API Kubernetes
kind: Service   # Type de ressource Kubernetes
metadata:
  labels:      # Étiquettes pour identifier le service
    app: web  # Nom de l'application associée
  name: web    # Nom du service
spec:
  ports:      # Configuration des ports du service
  - port: 3000  # Port sur lequel le service sera exposé
    protocol: TCP  # Protocole utilisé (TCP)
    targetPort: 8081  # Port cible sur lequel le service redirige le trafic
  selector:   # Sélecteur pour associer le service aux pods
    app: web  # Nom de l'application à sélectionner
